export interface Store{
    id: number,
    data_cadastro: string,
    nome: string,
    cnpj: string,
    segmento_id: number,
    email: string,
    cep: string,
    logradouro: string,
    numero: string,
    complemento: string,
    bairro: string,
    cidade_id: number,
    estado_id: number,
    telefone: string,
    whatsapp: string,
    site: any,
    instagram: any,
    twitter: any,
    facebook: any,
    raio_id: number,
    descricao: any,
    qtd_visitas: any,
    responsavel_nome: string,
    responsavel_celular: string,
    logo: "assets/images/restaurant1.jpg",
    capa: any,
    destaque: any,
    tempo_entrega: string,
   frase_slogan: any,
    taxa_entrega: 3,
    tempo_producao: string,
    tempo_estimado: string,
    tempo_final: string,
    visivel: string,
   numero_pedido: any,
    entrega_gratis: string
    raio:Object;

}